config/routes.rb
Rails.application.routes.draw do

  
  resources :locations

  root                    'static_pages#home'
  get     'about'   =>    'static_pages#about'
  get     'signup'  =>    'users#new'
  get     'contact' =>    'static_pages/contact'
  get     'login'   =>    'sessions#new'
  post    'login'   =>    'sessions#create'
  get  'logout'  =>    'sessions#destroy'
  
  resources :schedules do
    resources :feedbacks
  end
  
  resources :users

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  # extend SimpleCalendar
  # has_calendar attribute: :starts_attend
  
  validates_inclusion_of :time_of_day, in: Choices['time_of_day']

  belongs_to :location

  # belongs_to :user

  # accepts_nested_attributes_for :location

  has_many :feedbacks



end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  layout "schedules"
  

  before_action :set_schedule, only: [:show, :edit, :update, :destroy]


  # GET /schedules
  # GET /schedules.json
  def index
    @search = "2"
    if params[:search]
      @search = params[:search]
    end

    @schedules = Schedule.where(location_id: @search.to_i)
    
    @location = Location.find(@search.to_i)

    # if @search != nil
    #   @schedules = Schedule.where(:location => @search)
    # end
    # render :layout => 'dashboard'
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show

  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:start_time, :end_time, :time_of_day, :status)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time_of_day %><br>
    <%= f.select :time_of_day, Choices['time_of_day'] %>
  </div>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
	<div class="container pull right">You're currently viewing the schedule for: 
	<p ><%= @location.address %></p> <p id="searchParam" class="hidden"><%= @search %></p>
	</div>
	<p id="notice"><%= notice %></p>

		<div class="row">
			
			<div class="tiles row tiles-container red no-padding">
				
				<div class="tiles white no-padding">
					<div class="tiles-body">
						
						<div id="calendar"></div>
					</div>
				</div>

				<div class="tiles red no-padding">
					<div class="tiles-body">
						<div class="calender-options-wrapper">
							<h3 class="text-white semi-bold" id="calender-current-day"></h3>
							<h2 class="text-white" id="calender-current-date"></h2>
							<div id='external-events' class="hide-inphone events-wrapper">
								<div class="events-heading">&nbsp;This Week's Summary</div>
								<%# @schedules.each do |schedule| %>
								<%#= schedule.status.map { |key, value| !value.count  } %>
								<div class='external-event'>
								3 Off Days
								</div>
							
								<div class='external-event'>Monday, Tuesday, Wednesday</div>
								
							</div>
						</div>								
					</div>
				</div>
			</div>
		</div>
		<br>
	


	<br>

	<%= link_to 'New Schedule', new_schedule_path %>

	

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-10">
    <div class="grid simple horizontal purple">
      <div class="grid-title no-border">
        <h4>ECG <span class="semi-bold">Schedule</span></h4>
        <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
      </div>
      <div class="grid-body no-border">
        <div class="row-fluid">
          <div>
            <h3><%= Date::DAYNAMES[@schedule.start_time.wday] %>, <span class="semi-bold"><%= @schedule.start_time.to_date %></span></h3>
            <!-- <div class="color-bands green"></div>
            <div class="color-bands purple"></div>
            <div class="color-bands red"></div>
            <div class="color-bands blue"></div> -->
            <br>
            
            <h3> During the <strong><%= @schedule.time_of_day.capitalize %></strong>, between <br/>   
            </h3>         

            <h3>
              <strong><%= @schedule.start_time.strftime('%T') %></strong> and <strong><%= @schedule.end_time.strftime('%T') %></strong>
            </h3>

            <h3>
              <% if @schedule.status? %>
              <div class="color-bands green"></div>
              Lights ON
              <% else %>
              <div class="color-bands red"></div>
              Lights OUT
              <% end %>
            </h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-10">
    <div class="grid simple vertical purple">
      <div class="grid-title ">
        <h4>Users <span class="semi-bold">Feedback</span></h4>
        <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
      </div>
      <div class="grid-body">
        <div id="email-list">
          <table class="table table-striped table-fixed-layout table-hover" id="emails">
            <thead>
              <tr>                
                <th class="medium-cell"></th>
                <th></th>               
              </tr>
            </thead>
            <tbody>
            <% @schedule.feedbacks.each do |feedback| %>
              <tr>
                <td class="clickable v-align-middle"><%= feedback.user.name %></td>
                <td class="clickable v-align-middle"><% if (feedback.user_status == "This is accurate") %><span class="label label-success"><%= feedback.user_status %></span>&nbsp;
                  <% else %>
                  <span class="label label-important"><%= feedback.user_status %></span>&nbsp;
                  <% end %></td>   
                <% end %>              
              </tr>
              
            </tbody>
          </table>
                     
        </div>

        <div>
          <h4>Give your feedback, is this Accurate?</h4>
          <%= render "feedbacks/form" %>
        </div>

      </div>
    </div>
  </div>
  </div>





<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>