config/routes.rb
Rails.application.routes.draw do

  
  resources :locations

  root                    'static_pages#home'
  get     'about'   =>    'static_pages#about'
  get     'signup'  =>    'users#new'
  get     'contact' =>    'static_pages/contact'
  get     'login'   =>    'sessions#new'
  post    'login'   =>    'sessions#create'
  get  'logout'  =>    'sessions#destroy'
  
  resources :schedules do
    resources :feedbacks
  end
  
  resources :users

end

app/views/shared/_dashboard_header.html.erb
<div class="header navbar navbar-inverse ">

	<div class="navbar-inner">
		<div class="header-seperation">
			<ul class="nav pull-left notifcation-center" id="main-menu-toggle-wrapper" style="display:none">
				<li class="dropdown"> <a id="main-menu-toggle" href="#main-menu" class=""> <div class="iconset top-menu-toggle-white"></div> </a> </li>
			</ul>

			<div class="navbar-left">
                        
                        <!-- LOGO ON STICKY NAV BAR -->
                        
                        <!-- LOGO -->
                        <a class="navbar-brand">
                            <%= link_to image_tag("small6.png"), "/" %><span class="" style="text-color:white">DUMSOLY</span>
                        </a>
                        
            </div>

			
		</div>

		<div class="header-quick-nav">

			<div class="pull-left">
				
				<ul class="nav quick-section">
					
					<li class="m-r-10 input-prepend inside search-form no-boarder">
						<span class="add-on"> <span class="iconset top-search"></span></span>
						<input name="" type="text" class="no-boarder " placeholder="Search Dashboard" style="width:250px;">
					</li>
				</ul>
			</div>


			<div class="pull-right">
				<div class="chat-toggler">
					<a href="#" class="dropdown-toggle" id="my-task-list" data-placement="bottom" data-content='' data-toggle="dropdown" data-original-title="Notifications"> 
						<div class="user-details">
							<div class="username">
							<% if logged_in? %>
								<span class="badge badge-important">2</span>
								<%= @user.name %>
							</div>
						</div>
						<div class="iconset top-down-arrow"></div>
					</a>
					<div id="notification-list" style="display:none">
						<div style="width:300px">
							<div class="notification-messages info">
								<div class="user-profile">
									
								</div>
								<div class="message-wrapper">
									<div class="heading">
										Location: MEST Hostel, North Legon
									</div>
									<div class="description">
										Light on
									</div>
									<div class="date pull-left">
										in 12 hours
									</div>
								</div>
								<div class="clearfix"></div>
							</div>
							<div class="notification-messages danger">
								<div class="iconholder">
									<i class="icon-warning-sign"></i>
								</div>
								<div class="message-wrapper">
									<div class="heading">
										Location: MEST, East Legon
									</div>
									<div class="description">
										Light off
									</div>
									<div class="date pull-left">
										in 6 hours
									</div>
								</div>
								<div class="clearfix"></div>
							</div>
						</div>
					</div>

				</div>
				<ul class="nav quick-section ">

					<li class="quicklinks">
						<a data-toggle="dropdown" class="dropdown-toggle  pull-right " href="#" id="user-options">
							<div class="iconset top-settings-dark "><%= image_tag('settings3.png')%></div>
						</a>
						<ul class="dropdown-menu  pull-right" role="menu" aria-labelledby="user-options">
							<li><a href="user-profile.html"> My Account</a>
							</li>
							<li><%= link_to "My Calendar", schedules_path %>
							</li>
							<li><a href="email.html"> My Inbox&nbsp;&nbsp;<span class="badge badge-important animated bounceIn">2</span></a>
							</li>
							<li class="divider"></li>
							<li><%= link_to image_tag('logout.png') + " Log Out", logout_path %>

							</li>
							
						</ul>
					</li>

					<% else %>
			          <li><%= link_to "Log in", login_path %></li>
			        <% end %>
					
				</ul>
		</div>

	</div>

</div>

</div>

app/views/shared/_dashboard_sidebar.html.erb
<div class="page-sidebar" id="main-menu">

		<div class="page-sidebar-wrapper scrollbar-dynamic" id="main-menu-wrapper">
		<% if logged_in? %>
			<div class="user-info-wrapper">
				<div class="profile-wrapper"><%= gravatar_for @user %> </div>
				<div class="user-info">
					<div class="greeting">Welcome</div>
					<div class="username"><%= @user.name %></div>
					<div class="status">Status<a href="#">
						<div class="status-icon green"></div>
						Online</a></div>
					</div>
				</div>


				<ul>
					<li class="start"> <a href="index-2.html"> <i class="icon-custom-home"></i> <span class="title">Dashboard</span>  </a>
						
					</li>
					<li class=""> <a href="widgets.html"> <span class="title">Account Settings</span> <span class="label label-important pull-right "></span></a> 
					</li>
					
					<li class=""> <a href="email.html"> <span class="title">Notifications</span> <span class=" badge badge-disable pull-right ">2</span></a> 
					</li>
					
					
				</ul>
						
				
				<% else %>
		          <div class="clearfix"></div>
		        <% end %>

		</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_schedules_header.html.erb
<div class="header navbar navbar-inverse ">

	<div class="navbar-inner">
		<div class="header-seperation">
			<ul class="nav pull-left notifcation-center" id="main-menu-toggle-wrapper" style="display:none">
				<li class="dropdown"> <a id="main-menu-toggle" href="#main-menu" class=""> <div class="iconset top-menu-toggle-white"></div> </a> </li>
			</ul>

			<div class="navbar-left">
                        
                        <!-- LOGO ON STICKY NAV BAR -->
                        
                        <!-- LOGO -->
                        <a class="navbar-brand">
                            <%= link_to image_tag("small6.png"), "/" %><span class="" style="text-color:white">DUMSOLY</span>
                        </a>
                        
            </div>

			
		</div>

		<div class="header-quick-nav">

			<div class="pull-left">
				
				<ul class="nav quick-section">
					
					<li class="m-r-10 input-prepend inside search-form no-boarder">
						<span class="add-on"> <span class="iconset top-search"></span></span>
						<input name="" type="text" class="no-boarder " placeholder="Search Dashboard" style="width:250px;">
					</li>
				</ul>
			</div>

			<% if logged_in? %>
			<div class="pull-right">
				<div class="chat-toggler">
					<a href="#" class="dropdown-toggle" id="my-task-list" data-placement="bottom" data-content='' data-toggle="dropdown" data-original-title="Notifications"> 
						<div class="user-details">
							<div class="username">
								<span class="badge badge-important">2</span>
								<%= @current_user.name %>
							</div>
						</div>
						<div class="iconset top-down-arrow"></div>
					</a>
					<div id="notification-list" style="display:none">
						<div style="width:300px">
							<div class="notification-messages info">
								<div class="user-profile">
									
								</div>
								<div class="message-wrapper">
									<div class="heading">
										Location: MEST Hostel, North Legon
									</div>
									<div class="description">
										Light on
									</div>
									<div class="date pull-left">
										in 12 hours
									</div>
								</div>
								<div class="clearfix"></div>
							</div>
							<div class="notification-messages danger">
								<div class="iconholder">
									<i class="icon-warning-sign"></i>
								</div>
								<div class="message-wrapper">
									<div class="heading">
										Location: MEST, East Legon
									</div>
									<div class="description">
										Light off
									</div>
									<div class="date pull-left">
										in 6 hours
									</div>
								</div>
								<div class="clearfix"></div>
							</div>
						</div>
					</div>

				</div>
				<ul class="nav quick-section ">

					<li class="quicklinks">
						<a data-toggle="dropdown" class="dropdown-toggle  pull-right " href="#" id="user-options">
							<div class="iconset top-settings-dark "><%= image_tag('settings3.png')%></div>
						</a>
						<ul class="dropdown-menu  pull-right" role="menu" aria-labelledby="user-options">
							<li><a href="user-profile.html"> My Account</a>
							</li>
							<li><%= link_to "My Calendar", schedules_path %>
							</li>
							<li><a href="email.html"> My Inbox&nbsp;&nbsp;<span class="badge badge-important animated bounceIn">2</span></a>
							</li>
							<li class="divider"></li>
							<li><%= link_to image_tag('logout.png') + " Log Out", logout_path %>

							</li>
							
						</ul>
					</li>					
				</ul>
		<% else %>
		<div class="chat-toggler">
			
				<div class="user-details">
					<div class="username">
						<span class="badge badge-important"></span>
						Hello. Welcome to Dumsoly App.
					</div>
				</div>
				
		</div>
		<div class="navbar-collapse collapse" id="stamp-navigation">
                        
                        
            <!-- LOGIN REGISTER -->
            <ul class="nav navbar-nav navbar-right login-register small-text">
                <li class="login js-login"><%= link_to "Login",   login_path %></li>
                <li class="register-button js-register inpage-scroll"><%= link_to "Get Notifications", signup_path, class: "navbar-register-button"%></li>
            </ul>
        </div>
			
			

		</div>
		<% end %>

		</div>
		

	</div>

</div>

</div>

app/views/shared/_schedules_sidebar.html.erb
<div class="page-sidebar" id="main-menu">

		<div class="page-sidebar-wrapper scrollbar-dynamic" id="main-menu-wrapper">
		<% if logged_in? %>
			<div class="user-info-wrapper">
				<div class="profile-wrapper"><%= gravatar_for @current_user %> </div>
				<div class="user-info">
					<div class="greeting">Welcome</div>
					<div class="username"><%= @current_user.name %></div>
					<div class="status">Status<a href="#">
						<div class="status-icon green"></div>
						Online</a></div>
					</div>
				</div>


				<ul>
					<li class="start"> <a href="index-2.html"> <i class="icon-custom-home"></i> <span class="title">Dashboard</span>  </a>
						
					</li>
					<li class=""> <a href="widgets.html"> <span class="title">Account Settings</span> <span class="label label-important pull-right "></span></a> 
					</li>
					
					<li class=""> <a href="email.html"> <span class="title">Notifications</span> <span class=" badge badge-disable pull-right ">2</span></a> 
					</li>
					
					
				</ul>
						
				
				<% else %>
		          <div class="clearfix"></div>
		        <% end %>

		</div>
</div>