config/routes.rb
Rails.application.routes.draw do

  
  resources :locations

  root                    'static_pages#home'
  get     'about'   =>    'static_pages#about'
  get     'signup'  =>    'users#new'
  get     'contact' =>    'static_pages/contact'
  get     'login'   =>    'sessions#new'
  post    'login'   =>    'sessions#create'
  get  'logout'  =>    'sessions#destroy'
  
  resources :schedules do
    resources :feedbacks
  end
  
  resources :users

end

app/views/layouts/_footer.html.erb
 <!-- FOOTER -->
    <footer class="footer grey-bg">
        ©2014 Dumsoly App. All Rights Reserved
        
        <!-- OPTIONAL FOOTER LINKS -->
        <ul class="footer-links small-text">
            <li><%= link_to "How it works",   about_path, class: "dark-text" %></li>

            <li><a href="#" class="dark-text">Contact</a>
            </li>
            <li><a href="#" class="dark-text">Privacy</a>
            </li>
        </ul>
        
        <!-- SOCIAL ICONS -->
        <ul class="social-icons">
            <li><a href="#"><span class="icon-social-facebook transparent-text-dark"></span></a>
            </li>
            <li><a href="#"><span class="icon-social-twitter transparent-text-dark"></span></a>
            </li>
        </ul>
        
    </footer>
    

app/views/layouts/_header.html.erb
 <!-- STICKY NAVIGATION -->
            <div class="navbar navbar-inverse bs-docs-nav navbar-fixed-top sticky-navigation" role="navigation">
                <div class="container">
                    <div class="navbar-left">
                        
                        <!-- LOGO ON STICKY NAV BAR -->
                        
                        <!-- LOGO -->
                        <a class="navbar-brand">
                            <%= link_to image_tag("small6.png"), "/" %>DUMSOLY
                        </a>
                        
                    </div>
                    
                    <!-- TOP BAR -->
                    <div class="navbar-collapse collapse" id="stamp-navigation">
                        
                        
                        <!-- LOGIN REGISTER -->
                        <ul class="nav navbar-nav navbar-right login-register small-text">
                            <li class="login js-login"><%= link_to "Login",   login_path %></li>
                            <li class="register-button js-register inpage-scroll"><%= link_to "Get Notifications", signup_path, class: "navbar-register-button"%></li>
                        </ul>
                    </div>
                </div>
                <!-- /END CONTAINER -->
            </div>
            
            <!-- /END STICKY NAVIGATION -->

app/views/layouts/_shim.html.erb
	<!--[if lt IE 9]>
			<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
    <![endif]-->
    <!--[if gte IE 9]>
      <style type="text/css">
        .standard-button,
        .navbar-register-button {
       filter: none;
        }
      </style>
    <![endif]-->
    <!-- ****************
      After neccessary customization/modification, Please minify HTML/CSS according to http://browserdiet.com/en/ for better performance
     **************** -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width,initial-scale=1.0" name="viewport" />
  <meta content="My first Rails App" name="description"/>
  <meta content="Esther Olatunde" name="author"/>
  <%= render 'layouts/shim' %>
	 
</head>
<body>
	<%= render 'layouts/header' %>
	
	<%= yield %>
	
	<%= render 'layouts/footer' %>
	<%#= debug(params) if Rails.env.development? %>
	
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'dashboard', media: 'all' %>
  <%= javascript_include_tag 'dashboard' %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width,initial-scale=1.0" name="viewport" />
  <meta content="My first Rails App" name="description"/>
  <meta content="Esther Olatunde" name="author"/>
  <%= render 'layouts/shim' %>
	 
</head>
<body>
	<%#= render 'layouts/header' %>
	<%= render 'shared/dashboard_header' %>

	<div class="page-container row-fluid">

	<%= render 'shared/dashboard_sidebar' %>

	<div class="page-content">
 

	<div class="clearfix"></div>
	<div class="content">

	
	<%= yield %>
	
	<%#= render 'layouts/footer' %>
	<%#= debug(params) if Rails.env.development? %>
	
	</div>
	</div>
	</div>
	
	
</body>
</html>

app/views/layouts/schedules.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'dashboard', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width,initial-scale=1.0" name="viewport" />
  <meta content="My first Rails App" name="description"/>
  <meta content="Esther Olatunde" name="author"/>
  <%= render 'layouts/shim' %>
	 
</head>
<body>
	<%#= render 'layouts/header' %>
	<%= render 'shared/schedules_header' %>

	<div class="page-container row-fluid">

	<%= render 'shared/schedules_sidebar' %>

	<div class="page-content">
 

	<div class="clearfix"></div>
	<div class="content">

	
	<%= yield %>
	
	<%#= render 'layouts/footer' %>
	<%#= debug(params) if Rails.env.development? %>
	
	</div>
	</div>
	</div>
	
	
</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'dashboard', media: 'all' %>
  <%= javascript_include_tag 'dashboard' %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width,initial-scale=1.0" name="viewport" />
  <meta content="My first Rails App" name="description"/>
  <meta content="Esther Olatunde" name="author"/>
  <%= render 'layouts/shim' %>
	 
</head>
<body>
	<%= render 'layouts/header' %>
	<%#= render 'shared/dashboard' %>

	
	<div class="container">

	<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
	
	<%= yield %>
	
	<%#= render 'layouts/footer' %>
	<%#= debug(params) if Rails.env.development? %>
	
	</div>
	
</body>
</html>